"""Embedded MITRE ATT&CK technique reference data.

A focused subset of ATT&CK techniques relevant to the simulated attack
scenarios (account takeover, brute force, privilege escalation, malware,
data exfiltration). Each entry mirrors the structure of the official
ATT&CK knowledge base so the local dataset can later be replaced by a
live STIX/TAXII feed without changing consumers.
"""

MITRE_TECHNIQUES = [
    {
        "technique_id": "T1078",
        "name": "Valid Accounts",
        "tactic": "initial-access",
        "description": "Adversaries may obtain and abuse credentials of existing accounts as a means of gaining Initial Access, Persistence, Privilege Escalation, or Defense Evasion. Compromised credentials may be used to bypass access controls placed on various resources.",
        "detection": "Monitor for anomalous login activity, logon from unfamiliar devices or locations, and use of accounts outside of their normal behavioral baseline.",
        "severity_hint": "HIGH",
        "platforms": ["Windows", "Linux", "macOS", "Cloud"],
        "url": "https://attack.mitre.org/techniques/T1078/",
    },
    {
        "technique_id": "T1110",
        "name": "Brute Force",
        "tactic": "credential-access",
        "description": "Adversaries may use brute force techniques to gain access to accounts when passwords are unknown or when password hashes are obtained.",
        "detection": "Monitor for many failed authentication attempts across a short window, especially from a single source, and for lockout events.",
        "severity_hint": "HIGH",
        "platforms": ["Windows", "Linux", "macOS", "Cloud"],
        "url": "https://attack.mitre.org/techniques/T1110/",
    },
    {
        "technique_id": "T1110.001",
        "name": "Brute Force: Password Guessing",
        "tactic": "credential-access",
        "description": "Adversaries with no prior knowledge of legitimate credentials may guess a password to gain access to an account.",
        "detection": "Monitor authentication logs for repeated failed logins against the same account from the same source.",
        "severity_hint": "HIGH",
        "platforms": ["Windows", "Linux", "macOS", "Cloud"],
        "url": "https://attack.mitre.org/techniques/T1110/001/",
    },
    {
        "technique_id": "T1548",
        "name": "Abuse Elevation Control Mechanism",
        "tactic": "privilege-escalation",
        "description": "Adversaries may circumvent mechanisms designed to control elevated privileges to gain higher-level permissions. This often involves exploiting misconfigured sudoers, setuid, or UAC settings.",
        "detection": "Monitor for unexpected elevation of privileges, new admin group membership, or changes to privilege control configurations.",
        "severity_hint": "HIGH",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1548/",
    },
    {
        "technique_id": "T1548.002",
        "name": "Abuse Elevation Control Mechanism: Bypass User Account Control",
        "tactic": "privilege-escalation",
        "description": "Adversaries may bypass UAC mechanisms to elevate privileges without prompting the user.",
        "detection": "Monitor process creation events for unusual parent-child relationships and for processes spawned from trusted directories.",
        "severity_hint": "HIGH",
        "platforms": ["Windows"],
        "url": "https://attack.mitre.org/techniques/T1548/002/",
    },
    {
        "technique_id": "T1068",
        "name": "Exploitation for Privilege Escalation",
        "tactic": "privilege-escalation",
        "description": "Adversaries may exploit software vulnerabilities in an attempt to elevate privileges.",
        "detection": "Monitor for unusual process behavior, crashes, and unexpected service or binary execution indicative of exploitation attempts.",
        "severity_hint": "CRITICAL",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1068/",
    },
    {
        "technique_id": "T1021",
        "name": "Remote Services",
        "tactic": "lateral-movement",
        "description": "Adversaries may use valid accounts to log into remote services such as RDP, SSH, and VNC to move laterally within an environment.",
        "detection": "Monitor for new remote login sessions, especially outside business hours or from unexpected source IPs.",
        "severity_hint": "HIGH",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1021/",
    },
    {
        "technique_id": "T1021.001",
        "name": "Remote Services: Remote Desktop Protocol",
        "tactic": "lateral-movement",
        "description": "Adversaries may use valid credentials to log into a remote machine via RDP.",
        "detection": "Monitor RDP logon events and new incoming RDP connections.",
        "severity_hint": "HIGH",
        "platforms": ["Windows"],
        "url": "https://attack.mitre.org/techniques/T1021/001/",
    },
    {
        "technique_id": "T1041",
        "name": "Exfiltration Over C2 Channel",
        "tactic": "exfiltration",
        "description": "Adversaries may steal data by exfiltrating it over an existing command and control channel, blending exfiltration traffic with C2 traffic.",
        "detection": "Monitor for unusually large outbound transfers and connections to known-bad domains or IPs.",
        "severity_hint": "CRITICAL",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1041/",
    },
    {
        "technique_id": "T1567",
        "name": "Exfiltration Over Web Service",
        "tactic": "exfiltration",
        "description": "Adversaries may exfiltrate data to a cloud storage or web service rather than over their primary C2 channel.",
        "detection": "Monitor for large uploads to external web services and for anomalous API usage patterns.",
        "severity_hint": "CRITICAL",
        "platforms": ["Windows", "Linux", "macOS", "Cloud"],
        "url": "https://attack.mitre.org/techniques/T1567/",
    },
    {
        "technique_id": "T1030",
        "name": "Data Transfer Size Limits",
        "tactic": "exfiltration",
        "description": "Adversaries may break exfiltration into smaller packets to avoid triggering network transfer size thresholds.",
        "detection": "Monitor for many small outbound transfers to the same destination within a short time window.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1030/",
    },
    {
        "technique_id": "T1027",
        "name": "Obfuscated Files or Information",
        "tactic": "defense-evasion",
        "description": "Adversaries may attempt to make artifacts or activity difficult to discover by obfuscating data, code, or other indicators.",
        "detection": "Monitor for suspicious file types, packed binaries, and encoding utilities invoked from unusual contexts.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1027/",
    },
    {
        "technique_id": "T1204",
        "name": "User Execution",
        "tactic": "execution",
        "description": "An adversary may rely on a user opening a malicious file or executing a malicious script to trigger execution.",
        "detection": "Monitor for execution of suspicious documents or scripts, and for processes spawned from email or web downloads.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1204/",
    },
    {
        "technique_id": "T1059",
        "name": "Command and Scripting Interpreter",
        "tactic": "execution",
        "description": "Adversaries may abuse command and script interpreters to execute commands, scripts, or binaries.",
        "detection": "Monitor for execution of shells, PowerShell, Python, and scripting interpreters from anomalous contexts.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1059/",
    },
    {
        "technique_id": "T1059.001",
        "name": "Command and Scripting Interpreter: PowerShell",
        "tactic": "execution",
        "description": "Adversaries may abuse PowerShell to execute arbitrary code, often with obfuscated command lines.",
        "detection": "Monitor PowerShell execution, especially with encoded commands, script block logging, and unusual module loads.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows"],
        "url": "https://attack.mitre.org/techniques/T1059/001/",
    },
    {
        "technique_id": "T1003",
        "name": "OS Credential Dumping",
        "tactic": "credential-access",
        "description": "Adversaries may attempt to dump credentials to obtain account login and credential material, normally in the form of a hash or a clear-text password.",
        "detection": "Monitor for processes accessing LSASS memory, SAM/SYSTEM registry hives, or credential files.",
        "severity_hint": "CRITICAL",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1003/",
    },
    {
        "technique_id": "T1078.004",
        "name": "Valid Accounts: Cloud Accounts",
        "tactic": "initial-access",
        "description": "Adversaries may obtain and abuse credentials of cloud accounts as a means of gaining initial access.",
        "detection": "Monitor cloud identity provider logs for anomalous sign-ins, new API keys, and privilege changes.",
        "severity_hint": "HIGH",
        "platforms": ["Cloud"],
        "url": "https://attack.mitre.org/techniques/T1078/004/",
    },
    {
        "technique_id": "T1071",
        "name": "Application Layer Protocol",
        "tactic": "command-and-control",
        "description": "Adversaries may communicate using OSI application layer protocols to avoid detection by blending in with existing traffic.",
        "detection": "Monitor for anomalous communications patterns, unusual domains, and beaconing behavior.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1071/",
    },
    {
        "technique_id": "T1071.001",
        "name": "Application Layer Protocol: Web Protocols",
        "tactic": "command-and-control",
        "description": "Adversaries may communicate using HTTP/HTTPS to blend C2 traffic with legitimate web traffic.",
        "detection": "Monitor for periodic beaconing to external hosts, unusual user agents, and POST requests with encrypted payloads.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1071/001/",
    },
    {
        "technique_id": "T1219",
        "name": "Remote Access Software",
        "tactic": "command-and-control",
        "description": "Adversaries may use legitimate remote access software to establish interactive C2.",
        "detection": "Monitor for installation and execution of remote administration tools not used by the organization.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1219/",
    },
    {
        "technique_id": "T1552",
        "name": "Unsecured Credentials",
        "tactic": "credential-access",
        "description": "Adversaries may search compromised systems for insecurely stored credentials, including files, environment variables, and configuration stores.",
        "detection": "Monitor for access to credential stores, config files containing secrets, and environment variable dumps.",
        "severity_hint": "HIGH",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1552/",
    },
    {
        "technique_id": "T1555",
        "name": "Credentials from Password Stores",
        "tactic": "credential-access",
        "description": "Adversaries may search for common password storage locations and obtain credentials.",
        "detection": "Monitor for access to browser credential stores, password managers, and keychain databases.",
        "severity_hint": "HIGH",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1555/",
    },
    {
        "technique_id": "T1566",
        "name": "Phishing",
        "tactic": "initial-access",
        "description": "Adversaries may send phishing messages to gain access to victim systems.",
        "detection": "Monitor email gateway logs for malicious attachments/links and for users clicking on suspicious URLs.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1566/",
    },
    {
        "technique_id": "T1566.001",
        "name": "Phishing: Spearphishing Attachment",
        "tactic": "initial-access",
        "description": "Adversaries may send spearphishing emails with a malicious attachment to gain access to victim systems.",
        "detection": "Monitor for opening of unexpected attachments, macro execution, and downloads triggered from email.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1566/001/",
    },
    {
        "technique_id": "T1190",
        "name": "Exploit Public-Facing Application",
        "tactic": "initial-access",
        "description": "Adversaries may attempt to exploit a weakness in an Internet-facing computer or program to gain access.",
        "detection": "Monitor web and application logs for exploit attempts, unusual requests, and unexpected error patterns.",
        "severity_hint": "HIGH",
        "platforms": ["Windows", "Linux", "macOS", "Cloud"],
        "url": "https://attack.mitre.org/techniques/T1190/",
    },
    {
        "technique_id": "T1046",
        "name": "Network Service Discovery",
        "tactic": "discovery",
        "description": "Adversaries may attempt to get a listing of services running on remote hosts, including those that may be vulnerable to remote software exploitation.",
        "detection": "Monitor for port scanning activity and connections to many hosts on the same ports in a short window.",
        "severity_hint": "LOW",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1046/",
    },
    {
        "technique_id": "T1018",
        "name": "Remote System Discovery",
        "tactic": "discovery",
        "description": "Adversaries may attempt to get a listing of other systems by IP address, hostname, or other logical identifier on a network.",
        "detection": "Monitor for network reconnaissance activity such as NetBIOS, AD enumeration, and DNS queries for many hosts.",
        "severity_hint": "LOW",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1018/",
    },
    {
        "technique_id": "T1083",
        "name": "File and Directory Discovery",
        "tactic": "discovery",
        "description": "Adversaries may enumerate files and directories to understand the environment and locate sensitive data.",
        "detection": "Monitor for enumeration of file shares, sensitive directories, and document repositories.",
        "severity_hint": "LOW",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1083/",
    },
    {
        "technique_id": "T1087",
        "name": "Account Discovery",
        "tactic": "discovery",
        "description": "Adversaries may attempt to get a listing of valid accounts, usernames, or email addresses on a system or within a domain.",
        "detection": "Monitor for enumeration of user accounts and groups, especially via directory services.",
        "severity_hint": "LOW",
        "platforms": ["Windows", "Linux", "macOS", "Cloud"],
        "url": "https://attack.mitre.org/techniques/T1087/",
    },
    {
        "technique_id": "T1530",
        "name": "Data from Cloud Storage Object",
        "tactic": "collection",
        "description": "Adversaries may access data objects from improperly secured cloud storage.",
        "detection": "Monitor for anomalous access patterns to cloud storage buckets and data objects.",
        "severity_hint": "HIGH",
        "platforms": ["Cloud"],
        "url": "https://attack.mitre.org/techniques/T1530/",
    },
    {
        "technique_id": "T1560",
        "name": "Archive Collected Data",
        "tactic": "collection",
        "description": "Adversaries may compress and/or encrypt data collected prior to exfiltration, often using utilities such as zip.",
        "detection": "Monitor for creation of archive files in unusual locations or by unusual processes.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1560/",
    },
    {
        "technique_id": "T1505",
        "name": "Server Software Component",
        "tactic": "persistence",
        "description": "Adversaries may abuse legitimate extensible development features of servers to establish persistent access.",
        "detection": "Monitor for new modules, plugins, or scripts added to server software.",
        "severity_hint": "HIGH",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1505/",
    },
    {
        "technique_id": "T1053",
        "name": "Scheduled Task/Job",
        "tactic": "persistence",
        "description": "Adversaries may abuse task scheduling functionality to initiate execution at specified intervals or in response to events.",
        "detection": "Monitor for creation of new scheduled tasks and jobs, especially pointing to unusual binaries.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1053/",
    },
    {
        "technique_id": "T1547",
        "name": "Boot or Logon Autostart Execution",
        "tactic": "persistence",
        "description": "Adversaries may configure system settings to automatically execute a program during system boot or logon.",
        "detection": "Monitor for new autostart entries in registry, startup folders, and launch agents.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1547/",
    },
    {
        "technique_id": "T1485",
        "name": "Data Destruction",
        "tactic": "impact",
        "description": "Adversaries may destroy data and files on specific systems or in large numbers to interrupt availability.",
        "detection": "Monitor for mass file deletion, disk wiping utilities, and destructive command execution.",
        "severity_hint": "CRITICAL",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1485/",
    },
    {
        "technique_id": "T1486",
        "name": "Data Encrypted for Impact",
        "tactic": "impact",
        "description": "Adversaries may encrypt data on target systems or on large numbers of systems to interrupt availability (ransomware).",
        "detection": "Monitor for mass file renames, new file extensions, and ransomware notes.",
        "severity_hint": "CRITICAL",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1486/",
    },
    {
        "technique_id": "T1498",
        "name": "Network Denial of Service",
        "tactic": "impact",
        "description": "Adversaries may perform network denial of service attacks to degrade or block availability of targeted resources.",
        "detection": "Monitor for abnormally high inbound traffic volume and unusual packet rates.",
        "severity_hint": "HIGH",
        "platforms": ["Windows", "Linux", "macOS", "Cloud"],
        "url": "https://attack.mitre.org/techniques/T1498/",
    },
    {
        "technique_id": "T1090",
        "name": "Proxy",
        "tactic": "command-and-control",
        "description": "Adversaries may use a connection proxy to direct network traffic between systems while concealing the true source.",
        "detection": "Monitor for traffic routed through known proxy services and for unusual TTL or header anomalies.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows", "Linux", "macOS", "Cloud"],
        "url": "https://attack.mitre.org/techniques/T1090/",
    },
    {
        "technique_id": "T1048",
        "name": "Exfiltration Over Alternative Protocol",
        "tactic": "exfiltration",
        "description": "Adversaries may steal data using an alternative protocol that does not match the primary C2 channel.",
        "detection": "Monitor for outbound traffic on unusual protocols or ports and for DNS tunneling.",
        "severity_hint": "CRITICAL",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1048/",
    },
    {
        "technique_id": "T1136",
        "name": "Create Account",
        "tactic": "persistence",
        "description": "Adversaries may create an account to maintain access to victim systems.",
        "detection": "Monitor for creation of new accounts, especially with elevated privileges.",
        "severity_hint": "HIGH",
        "platforms": ["Windows", "Linux", "macOS", "Cloud"],
        "url": "https://attack.mitre.org/techniques/T1136/",
    },
    {
        "technique_id": "T1098",
        "name": "Account Manipulation",
        "tactic": "persistence",
        "description": "Adversaries may manipulate accounts to maintain access, including adding credentials or changing permissions.",
        "detection": "Monitor for permission changes, added credentials, and changes to account attributes.",
        "severity_hint": "HIGH",
        "platforms": ["Windows", "Linux", "macOS", "Cloud"],
        "url": "https://attack.mitre.org/techniques/T1098/",
    },
    {
        "technique_id": "T1112",
        "name": "Modify Registry",
        "tactic": "defense-evasion",
        "description": "Adversaries may interact with the Windows Registry to hide configuration information or remove indicators.",
        "detection": "Monitor registry modifications, especially to run keys and security settings.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows"],
        "url": "https://attack.mitre.org/techniques/T1112/",
    },
    {
        "technique_id": "T1562",
        "name": "Impair Defenses",
        "tactic": "defense-evasion",
        "description": "Adversaries may maliciously modify components of a victim environment to hinder or disable defensive mechanisms.",
        "detection": "Monitor for disabled security tools, changed firewall rules, and stopped security services.",
        "severity_hint": "HIGH",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1562/",
    },
    {
        "technique_id": "T1036",
        "name": "Masquerading",
        "tactic": "defense-evasion",
        "description": "Adversaries may manipulate the name or metadata of a binary or file to make it appear legitimate.",
        "detection": "Monitor for execution of renamed binaries and for files with mismatched extensions or signatures.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1036/",
    },
    {
        "technique_id": "T1187",
        "name": "Forced Authentication",
        "tactic": "credential-access",
        "description": "Adversaries may gather authentication material by triggering a network authentication attempt from a target.",
        "detection": "Monitor for outbound SMB/NTLM authentication requests to unexpected hosts.",
        "severity_hint": "HIGH",
        "platforms": ["Windows"],
        "url": "https://attack.mitre.org/techniques/T1187/",
    },
    {
        "technique_id": "T1558",
        "name": "Steal or Forge Kerberos Tickets",
        "tactic": "credential-access",
        "description": "Adversaries may steal or forge Kerberos tickets to bypass authentication controls.",
        "detection": "Monitor for anomalous Kerberos ticket requests, golden/silver ticket artifacts, and unusual TGT usage.",
        "severity_hint": "CRITICAL",
        "platforms": ["Windows"],
        "url": "https://attack.mitre.org/techniques/T1558/",
    },
    {
        "technique_id": "T1570",
        "name": "Lateral Tool Transfer",
        "tactic": "lateral-movement",
        "description": "Adversaries may transfer tools or other files between systems in a compromised environment.",
        "detection": "Monitor for large file transfers between internal hosts and for execution of transferred binaries.",
        "severity_hint": "MEDIUM",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1570/",
    },
    {
        "technique_id": "T1021.002",
        "name": "Remote Services: SMB/Windows Admin Shares",
        "tactic": "lateral-movement",
        "description": "Adversaries may use valid accounts to interact with remote systems over SMB to move laterally.",
        "detection": "Monitor for SMB administrative share access and service creation on remote hosts.",
        "severity_hint": "HIGH",
        "platforms": ["Windows"],
        "url": "https://attack.mitre.org/techniques/T1021/002/",
    },
    {
        "technique_id": "T1203",
        "name": "Exploitation for Client Execution",
        "tactic": "execution",
        "description": "Adversaries may exploit software vulnerabilities in client applications to execute code.",
        "detection": "Monitor for crashes and unusual behavior of client applications (browsers, office suites, media players).",
        "severity_hint": "HIGH",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1203/",
    },
    {
        "technique_id": "T1133",
        "name": "External Remote Services",
        "tactic": "initial-access",
        "description": "Adversaries may leverage externally accessible remote services (VPN, Citrix, OWA) to gain initial access.",
        "detection": "Monitor for anomalous logins to external-facing remote services, especially from new IPs or at unusual times.",
        "severity_hint": "HIGH",
        "platforms": ["Windows", "Linux", "macOS", "Cloud"],
        "url": "https://attack.mitre.org/techniques/T1133/",
    },
    {
        "technique_id": "T1082",
        "name": "System Information Discovery",
        "tactic": "discovery",
        "description": "An adversary may attempt to get detailed information about the operating system and hardware of a compromised system.",
        "detection": "Monitor for execution of system information gathering commands.",
        "severity_hint": "LOW",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1082/",
    },
    {
        "technique_id": "T1005",
        "name": "Data from Local System",
        "tactic": "collection",
        "description": "Adversaries may search local system sources, such as file systems and local databases, to find files of interest and sensitive data prior to exfiltration.",
        "detection": "Monitor for unusual access to sensitive files, databases, and document repositories by accounts without a prior history of such access.",
        "severity_hint": "HIGH",
        "platforms": ["Windows", "Linux", "macOS"],
        "url": "https://attack.mitre.org/techniques/T1005/",
    },
]

TACTICS = [
    "reconnaissance",
    "resource-development",
    "initial-access",
    "execution",
    "persistence",
    "privilege-escalation",
    "defense-evasion",
    "credential-access",
    "discovery",
    "lateral-movement",
    "collection",
    "command-and-control",
    "exfiltration",
    "impact",
]


def get_technique(technique_id: str):
    for t in MITRE_TECHNIQUES:
        if t["technique_id"] == technique_id:
            return t
    return None
