import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { AlertTriangle } from "lucide-react";
import { api } from "../services/api";
import { Card, EmptyState, SeverityBadge, Skeleton, StatusBadge } from "../components/ui";
import type { Alert, Paginated } from "../types";

export default function Alerts() {
  const [page, setPage] = useState(1);
  const [severity, setSeverity] = useState("");
  const [status, setStatus] = useState("");

  const { data, isLoading } = useQuery({
    queryKey: ["alerts", page, severity, status],
    queryFn: async () => {
      const params: Record<string, string | number> = { page, page_size: 20 };
      if (severity) params.severity = severity;
      if (status) params.status = status;
      return (await api.get<Paginated<Alert>>("/alerts", { params })).data;
    },
  });

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-3">
        <h2 className="text-lg font-bold text-slate-100">Alert Queue</h2>
        <select className="input w-auto" value={severity} onChange={(e) => { setSeverity(e.target.value); setPage(1); }}>
          <option value="">All severities</option>
          {["LOW", "MEDIUM", "HIGH", "CRITICAL"].map((s) => <option key={s}>{s}</option>)}
        </select>
        <select className="input w-auto" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}>
          <option value="">All statuses</option>
          {["OPEN", "INVESTIGATING", "RESOLVED", "CLOSED"].map((s) => <option key={s}>{s}</option>)}
        </select>
      </div>

      <Card>
        {isLoading && !data ? (
          <div className="space-y-2">{[...Array(8)].map((_, i) => <Skeleton key={i} className="h-12" />)}</div>
        ) : !data || data.items.length === 0 ? (
          <EmptyState icon={<AlertTriangle className="h-8 w-8" />} title="No alerts" description="Alerts generated by the Detection Agent appear here." />
        ) : (
          <div className="overflow-x-auto">
            <table className="table-base">
              <thead>
                <tr>
                  <th>Alert ID</th><th>Title</th><th>Severity</th><th>Status</th><th>Category</th>
                  <th>Confidence</th><th>Events</th><th>Created</th>
                </tr>
              </thead>
              <tbody>
                {data.items.map((a) => (
                  <tr key={a.id}>
                    <td className="font-mono text-xs text-electric-400">{a.alert_id}</td>
                    <td className="max-w-[280px] truncate font-medium text-slate-200">{a.title}</td>
                    <td><SeverityBadge severity={a.severity} /></td>
                    <td><StatusBadge status={a.status} /></td>
                    <td className="text-xs text-slate-400">{a.category}</td>
                    <td className="font-mono text-xs">{(a.confidence * 100).toFixed(0)}%</td>
                    <td className="font-mono text-xs">{a.source_event_ids.length}</td>
                    <td className="whitespace-nowrap text-xs text-slate-500">{new Date(a.created_at).toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {data && (
          <div className="mt-4 flex items-center justify-between text-xs text-slate-500">
            <span>Page {data.page} of {data.pages} · {data.total} alerts</span>
            <div className="flex gap-2">
              <button className="btn-ghost" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>Prev</button>
              <button className="btn-ghost" disabled={page >= data.pages} onClick={() => setPage((p) => p + 1)}>Next</button>
            </div>
          </div>
        )}
      </Card>
    </div>
  );
}
