import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { Download, Eye, FileText, Loader2, PlusCircle } from "lucide-react";
import { api, getErrorMessage } from "../services/api";
import { useToast } from "../components/ui/Toast";
import { Card, EmptyState, Modal, Skeleton, StatusBadge } from "../components/ui";
import type { Incident, Paginated, Report, ReportDetail } from "../types";

export default function IncidentReports() {
  const { success, error: toastError } = useToast();
  const queryClient = useQueryClient();
  const navigate = useNavigate();
  const [page, setPage] = useState(1);
  const [busyIncident, setBusyIncident] = useState<string | null>(null);
  const [viewing, setViewing] = useState<ReportDetail | null>(null);

  const { data: reports } = useQuery({
    queryKey: ["reports", page],
    queryFn: async () => (await api.get<Paginated<Report>>("/reports", { params: { page, page_size: 20 } })).data,
  });

  const { data: incidents } = useQuery({
    queryKey: ["incidents", "reports"],
    queryFn: async () => (await api.get<Paginated<Incident>>("/incidents", { params: { page: 1, page_size: 50 } })).data,
  });

  const generate = async (incidentId: string) => {
    setBusyIncident(incidentId);
    try {
      const res = await api.post<ReportDetail>(`/reports/${incidentId}/generate`);
      success("Report generated", res.data.report.report_id);
      queryClient.invalidateQueries({ queryKey: ["reports"] });
    } catch (err) {
      toastError("Generation failed", getErrorMessage(err));
    } finally {
      setBusyIncident(null);
    }
  };

  const view = async (id: string) => {
    try {
      const res = await api.get<ReportDetail>(`/reports/${id}`);
      setViewing(res.data);
    } catch (err) {
      toastError("Could not open report", getErrorMessage(err));
    }
  };

  const download = (id: string) => {
    window.open(`/api/reports/${id}/pdf`, "_blank");
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-3">
        <FileText className="h-5 w-5 text-electric-400" />
        <h2 className="text-lg font-bold text-slate-100">Incident Reports</h2>
        <p className="text-xs text-slate-500">Automated PDF reports generated by the Report Agent</p>
        <select
          className="input ml-auto w-auto"
          onChange={(e) => e.target.value && generate(e.target.value)}
          value=""
        >
          <option value="">Generate report for…</option>
          {incidents?.items.map((inc) => (
            <option key={inc.id} value={inc.id}>{inc.incident_id} — {inc.title}</option>
          ))}
        </select>
      </div>

      <Card>
        {!reports ? (
          <div className="space-y-2">{[...Array(6)].map((_, i) => <Skeleton key={i} className="h-12" />)}</div>
        ) : reports.items.length === 0 ? (
          <EmptyState
            icon={<FileText className="h-8 w-8" />}
            title="No reports yet"
            description="Reports are generated automatically at the end of each incident pipeline."
          />
        ) : (
          <div className="overflow-x-auto">
            <table className="table-base">
              <thead>
                <tr><th>Report ID</th><th>Title</th><th>Incident</th><th>Created</th><th>By</th><th>Actions</th></tr>
              </thead>
              <tbody>
                {reports.items.map((r) => (
                  <tr key={r.id}>
                    <td className="font-mono text-xs text-electric-400">{r.report_id}</td>
                    <td className="text-sm font-medium text-slate-200">{r.title}</td>
                    <td className="font-mono text-xs text-slate-500">{r.incident_id.slice(0, 8)}</td>
                    <td className="whitespace-nowrap text-xs text-slate-500">{new Date(r.created_at).toLocaleString()}</td>
                    <td className="text-xs text-slate-500">{r.created_by ?? "—"}</td>
                    <td>
                      <div className="flex gap-2">
                        <button className="btn-ghost px-2.5 py-1 text-xs" onClick={() => view(r.id)}>
                          <Eye className="h-3.5 w-3.5" /> View
                        </button>
                        <button className="btn-ghost px-2.5 py-1 text-xs" onClick={() => download(r.id)}>
                          <Download className="h-3.5 w-3.5" /> PDF
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {reports && (
          <div className="mt-4 flex items-center justify-between text-xs text-slate-500">
            <span>Page {reports.page} of {reports.pages} · {reports.total} reports</span>
            <div className="flex gap-2">
              <button className="btn-ghost" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>Prev</button>
              <button className="btn-ghost" disabled={page >= reports.pages} onClick={() => setPage((p) => p + 1)}>Next</button>
            </div>
          </div>
        )}
      </Card>

      {/* Unreported incidents quick actions */}
      {incidents && incidents.items.length > 0 && (
        <Card title="Quick report generation">
          <div className="grid gap-2 md:grid-cols-2">
            {incidents.items.slice(0, 8).map((inc) => (
              <div key={inc.id} className="flex items-center gap-3 rounded-lg bg-night-850/60 px-3 py-2">
                <div className="min-w-0 flex-1">
                  <p className="truncate text-xs font-semibold text-slate-200">{inc.title}</p>
                  <p className="text-[10px] text-slate-600">{inc.incident_id} · {inc.category}</p>
                </div>
                <StatusBadge status={inc.status} />
                <button className="btn-ghost px-2.5 py-1 text-xs" disabled={busyIncident !== null} onClick={() => generate(inc.id)}>
                  {busyIncident === inc.id ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <PlusCircle className="h-3.5 w-3.5" />}
                  Generate
                </button>
                <button className="btn-ghost px-2.5 py-1 text-xs" onClick={() => navigate(`/incidents/${inc.id}`)}>Open</button>
              </div>
            ))}
          </div>
        </Card>
      )}

      <Modal
        open={!!viewing}
        onClose={() => setViewing(null)}
        title={viewing?.report.title ?? "Report"}
        footer={
          viewing?.pdf_available ? (
            <button className="btn-primary" onClick={() => download(viewing.report.id)}>
              <Download className="h-4 w-4" /> Download PDF
            </button>
          ) : undefined
        }
      >
        {viewing && (
          <div className="text-xs leading-relaxed text-slate-400">
            <p><span className="font-semibold text-slate-200">Report:</span> {viewing.report.report_id}</p>
            <p><span className="font-semibold text-slate-200">Incident:</span> {(viewing.content.incident as { incident_id?: string } | undefined)?.incident_id ?? "—"}</p>
            <p><span className="font-semibold text-slate-200">Severity:</span> {(viewing.content.incident as { severity?: string } | undefined)?.severity ?? "—"}</p>
            <p><span className="font-semibold text-slate-200">Risk:</span> {(viewing.content.risk as { score?: number; severity_label?: string } | undefined)?.score ?? "—"} / 100 ({(viewing.content.risk as { severity_label?: string } | undefined)?.severity_label ?? "—"})</p>
            <p className="mt-2"><span className="font-semibold text-slate-200">Investigation summary:</span> {(viewing.content.investigation as { summary?: string } | undefined)?.summary ?? "—"}</p>
            <p className="mt-2"><span className="font-semibold text-slate-200">Verdict:</span> {(viewing.content.investigation as { verdict?: string } | undefined)?.verdict ?? "—"}</p>
            <div className="mt-3">
              <p className="mb-1 font-semibold text-slate-200">MITRE techniques:</p>
              {(viewing.content.mitre as Array<{ technique_id: string; name: string }> | undefined)?.map((m) => (
                <p key={m.technique_id}>• {m.technique_id} — {m.name}</p>
              )) ?? <p>None</p>}
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
}
